# Generated by Django 5.0.6 on 2024-06-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_id', models.IntegerField(blank=True, null=True)),
                ('peso', models.FloatField()),
                ('timestamp1', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
