# Generated by Django 5.0.6 on 2024-06-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_alter_temperaturasensores_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturasensores',
            name='sensor_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='temperaturasensores',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
